version: '3'
services:

  trillian-mysql:
    network_mode: host
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  trillian-map:
    network_mode: host
    depends_on:
      - trillian-mysql
    build:
      context: ./
      dockerfile: Dockerfile.trillian
    volumes:
      - ./:/go/src/github.com/google/trillian
    ports:
      - "8090:8090" # gRPC
      - "8091:8091" # HTTP & Metrics
    environment:
      MYSQL_HOST: 0.0.0.0
    command: go test ./...

#        && ./trillian_map_server
#          -
#          - --rpc_endpoint=0.0.0.0:8090
#          - --http_endpoint=0.0.0.0:8091
#          - --alsologtostderr
#          - --v=1
