FROM golang:1.11

RUN go get github.com/google/trillian

WORKDIR /go/src/github.com/google/trillian

RUN git fetch --all --tags --prune

RUN git checkout a493c51117a7e96b459a37c4981ac4795535549d

RUN go get -t -u -v ./... | true


